# Project-wide Gradle settings.

android.useAndroidX=true

# Build only one architecture
reactNativeArchitectures=arm64-v8a


# Hermes
hermesEnabled=true

# Edge to edge
edgeToEdgeEnabled=false

# Gradle performance
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configuration-cache=true

# Memory settings
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m